apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fortune-helm.fullname" . }}
  labels:
    {{- include "fortune-helm.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "fortune-helm.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        {{- include "fortune-helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - mountPath: "/fortune"
          name: {{ include "fortune-helm.fullname" . }}
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      volumes:
      - name: {{ include "fortune-helm.fullname" . }}
        persistentVolumeClaim:
          claimName: oleg-claim-helm
