apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "fortune-helm.fullname" . }}
spec:
  storageClassName: hcloud-volumes
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/fortune"
