apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oleg-claim-helm
spec:
  storageClassName: hcloud-volumes
  volumeName: {{ include "fortune-helm.fullname" . }}
  accessModes:
    - ReadWriteOnce
  resources:
      requests:
        storage: 3Gi
