apiVersion: v1
kind: Service
metadata:
  name: {{ include "fortune-helm.fullname" . }}
  labels:
    {{- include "fortune-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "fortune-helm.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      name: http
      port: {{ .Values.service.port }}
      targetPort: 80
