apiVersion: v1
kind: PersistentVolume
metadata:
  name: oleg-volume
spec:
  storageClassName: hcloud-volumes
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/fortune"
